Is this commit still relevant
hpi-swa-teaching/RichTextEditing pull request #100
Opened 2020-06-13 10:43 UTC by frcroth

Looks unmerged

2020-06-13 14:30 UTC, sirkrypt0 commented
Nice, I think we are definitely missing those

2020-06-13 14:31 UTC, sirkrypt0 requested changes

2020-06-13 14:31 UTC, sirkrypt0 commented on packages/RichTextEditing-Tests.package/RichTextEditorTests.class/instance/testUS60disableAutocompletion.st
> +							self deny: self editorModel wantsAutocompletion]
The indentation seems far to much

2020-06-13 14:31 UTC, sirkrypt0 commented on packages/RichTextEditing-Tests.package/RichTextEditorTests.class/instance/testUS60enableAutocompletion.st
> +							self assert: self editorModel wantsAutocompletion]
Indentation

2020-06-15 09:06 UTC, konradh commented
Yes, it is a acceptance test for the disabling autocompletion functionality and still relevant.

2020-06-15 11:57 UTC, sirkrypt0 approved these changes

2020-06-15 12:11 UTC, merged