date and time of the last save are stored and displayed
hpi-swa-teaching/RichTextEditing pull request #103
Opened 2020-06-14 17:31 UTC by oleschl

2020-06-14 18:41 UTC, j-hellenberg approved these changes

2020-06-14 20:31 UTC, sirkrypt0 requested changes

2020-06-14 20:31 UTC, sirkrypt0 commented on packages/RichTextEditing-Core.package/RichTextDocument.class/instance/isUnsavedDocument.st
> +as yet unclassified
Should be categorised

2020-06-14 20:38 UTC, frcroth commented on packages/RichTextEditing-Core.package/RichTextDocument.class/instance/isUnsavedDocument.st
> +as yet unclassified
categorize

2020-06-14 20:38 UTC, frcroth commented on packages/RichTextEditing-Core.package/RichTextDocument.class/instance/timeLastSaved..st
> +timeLastSaved: anObject
use an appropriate name instead of `anObject`

2020-06-15 10:32 UTC, frcroth approved these changes

2020-06-15 10:41 UTC, sirkrypt0 approved these changes

2020-06-15 11:18 UTC, merged