Implementing #91
hpi-swa-teaching/RichTextEditing pull request #121
Opened 2020-06-21 08:46 UTC by frcroth

2020-06-21 16:35 UTC, sirkrypt0 requested changes
Looks like there are many old tests that don't comply with our styling guide regarding dots at the end of methods

2020-06-21 16:35 UTC, sirkrypt0 commented on packages/RichTextEditing-Core.package/RichTextEditorModel.class/instance/buildWith..st
> +			self buildInfoButtonWith: aBuilder."
What is the purpose of that comment?

2020-06-21 16:35 UTC, sirkrypt0 commented on packages/RichTextEditing-Tests.package/RichTextEditorTestCase.class/instance/documentMenu.st
> +	^self editorModel openDocumentMenu.
Space after `^` (is this defined in our styleguide?)
```suggestion
	^ self editorModel openDocumentMenu.
```

2020-06-21 16:35 UTC, sirkrypt0 commented on packages/RichTextEditing-Tests.package/RichTextEditorTestCase.class/instance/fileMenu.st
> +	^self editorModel openFileMenu.
```suggestion
	^ self editorModel openFileMenu.
```

2020-06-21 16:35 UTC, sirkrypt0 commented on packages/RichTextEditing-Tests.package/RichTextEditorTestCase.class/instance/menuItemWithLabelExists..st
> +	self documentMenu submorphsDo: [:morph | labels add: morph contents].
I think collect is what we want here, so something like the following. Then we might also reduce this to one return statement containing the union and the anySatisfy
```suggestion
	labels := (self fileMenu submorphs collect: [:morph | morph contents]) union:
	    (self documentMenu submorphs collect: [:morph |morph contents]).
```

2020-06-21 16:35 UTC, sirkrypt0 commented on packages/RichTextEditing-Tests.package/RichTextEditorTestCase.class/instance/selectMenuItemByLabel..st
> +	^ (menuItems select: [:morph | morph contents = aLabel]) first
I think the same as above applies there

2020-06-21 16:35 UTC, sirkrypt0 commented on packages/RichTextEditing-Tests.package/RichTextEditorTests.class/instance/testUS04loadButtonExists.st
> +	self assert: (self menuItemWithLabelExists: 'Load').
Dot at the end
```suggestion
	self assert: (self menuItemWithLabelExists: 'Load')
```

2020-06-21 16:35 UTC, sirkrypt0 commented on packages/RichTextEditing-Tests.package/RichTextEditorTests.class/instance/testUS04saveAsButtonExists.st
> +	self assert: (self menuItemWithLabelExists: 'Save as').
Dot at the end
```suggestion
	self assert: (self menuItemWithLabelExists: 'Save as')
```

2020-06-21 16:35 UTC, sirkrypt0 commented on packages/RichTextEditing-Tests.package/RichTextEditorTests.class/instance/testUS04saveButtonExists.st
> +	self assert: (self menuItemWithLabelExists: 'Save').
Dot
```suggestion
	self assert: (self menuItemWithLabelExists: 'Save')
```

2020-06-21 16:35 UTC, sirkrypt0 commented on packages/RichTextEditing-Tests.package/RichTextEditorTests.class/instance/testUS07RedoButtonRedoesChanges.st
> +	| text |
Better use the instance method `text` instead of creating a new text (I'm sure that is a historic test, lets just change that now)

2020-06-21 16:35 UTC, sirkrypt0 commented on packages/RichTextEditing-Tests.package/RichTextEditorTests.class/instance/testUS07UndoButtonExists.st
> +	self assert: (self menuItemWithLabelExists: 'Undo').
Dot
```suggestion
	self assert: (self menuItemWithLabelExists: 'Undo')
```

2020-06-21 16:35 UTC, sirkrypt0 commented on packages/RichTextEditing-Tests.package/RichTextEditorTests.class/instance/testUS07UndoButtonUndoesChanges.st
>  	self assert: self editorText = ''.
Dot
```suggestion
	self assert: self editorText = ''
```

2020-06-21 16:35 UTC, sirkrypt0 commented on packages/RichTextEditing-Tests.package/RichTextEditorTests.class/instance/testUS24saveButtonSavesInImage.st
>  	self assert: (self editorSavesIncludeKey: self editorModel currentSaveName).
Dot
```suggestion
	self assert: (self editorSavesIncludeKey: self editorModel currentSaveName)
```

2020-06-21 16:35 UTC, sirkrypt0 commented on packages/RichTextEditing-Tests.package/RichTextEditorTests.class/instance/testUS46NewButtonExists.st
> +	self assert: (self menuItemWithLabelExists: self newButtonLabel).
Dot
```suggestion
	self assert: (self menuItemWithLabelExists: self newButtonLabel)
```

2020-06-21 16:35 UTC, sirkrypt0 commented on packages/RichTextEditing-Tests.package/RichTextEditorTests.class/instance/testUS63InfoButtonExists.st
> +	self assert: (self menuItemWithLabelExists: 'Document info').
Dot
```suggestion
	self assert: (self menuItemWithLabelExists: 'Document info')
```

2020-06-21 16:35 UTC, sirkrypt0 commented on packages/RichTextEditing-Tests.package/RichTextEditorTests.class/instance/testUS67HelpBrowserIsOpended.st
> +
We don't need that newline

2020-06-21 18:14 UTC, frcroth commented on packages/RichTextEditing-Tests.package/RichTextEditorTestCase.class/instance/documentMenu.st
> +	^self editorModel openDocumentMenu.
Is not defined there, maybe you could change that

2020-06-21 19:36 UTC, sirkrypt0 approved these changes
Nice

2020-06-25 12:47 UTC, konradh approved these changes

2020-06-25 12:50 UTC, oleschl commented on packages/RichTextEditing-Tests.package/RichTextEditorTestCase.class/instance/menuItemWithLabelExists..st
> +	| labels |
extendability?

2020-06-25 12:52 UTC, oleschl approved these changes

2020-06-25 13:00 UTC, merged