Add keymap preference
hpi-swa-teaching/RichTextEditing pull request #178
Opened 2020-08-06 16:51 UTC by sirkrypt0

2020-08-06 17:47 UTC, frcroth commented
Can be merged IMO

2020-08-07 07:46 UTC, sirkrypt0 commented
should have tests

2020-08-07 08:04 UTC, frcroth commented
> 
> 
> should have tests

Are you working on this?

2020-08-07 09:40 UTC, oleschl approved these changes

2020-08-07 10:39 UTC, frcroth requested changes

2020-08-07 10:39 UTC, frcroth commented on packages/RichTextEditing-Tests.package/RichTextEditorTests.class/instance/setUp.st
> +resources
Change to running

2020-08-07 10:39 UTC, frcroth commented on packages/RichTextEditing-Tests.package/RichTextEditorTests.class/instance/structureKeymapPreference.st
> +	^ (self textEditor class asString , '>>', 'structureKeymap') asSymbol
What's that?

2020-08-07 10:39 UTC, frcroth commented on packages/RichTextEditing-Tests.package/RichTextEditorTests.class/instance/tearDown.st
> +resources
running

2020-08-07 11:20 UTC, frcroth approved these changes

2020-08-07 11:28 UTC, merged